import type { OnboardingTask } from "./types";

export const mockTasks: OnboardingTask[] = [
  {
    id: "task-contract-handover",
    title: "移交客戶合約細節",
    description:
      "彙整重點客戶的合約期限、付款條件、續約窗口與客製承諾，並由法務確認特殊條款。",
    status: "進行中",
    deadline: "2026-07-27",
    estimateHours: 6,
    department: "法務",
    sourceDocument: "客戶合約交接清單_v3.pdf",
    isBlocking: true,
    riskLevel: "high",
    crossDeptDependencyCount: 2,
    prerequisites: [
      {
        taskId: "external-customer-signoff",
        taskTitle: "取得客戶續約條款確認",
        status: "進行中",
        dependentDept: "業務",
        dependentOwner: "陳怡君",
        waitingOn: "等待客戶法務簽回續約條款確認書",
      },
    ],
    priority: "P0",
    priorityReason: "合約特殊承諾會影響後續客服回覆與續約報價。",
    relatedRiskIds: ["risk-contract-commitment", "risk-external-signoff"],
  },
  {
    id: "task-finance-reconciliation",
    title: "同步財務對帳流程",
    description:
      "交接每月對帳時程、發票開立規則、未收款追蹤方式及異常帳款的核准窗口。",
    status: "待處理",
    deadline: "2026-07-29",
    estimateHours: 5,
    department: "財務",
    sourceDocument: "月結與應收帳款SOP.docx",
    isBlocking: true,
    riskLevel: "high",
    crossDeptDependencyCount: 1,
    prerequisites: [
      {
        taskId: "task-contract-handover",
        taskTitle: "移交客戶合約細節",
        status: "進行中",
        dependentDept: "法務",
        dependentOwner: "林冠宇",
      },
    ],
    priority: "P0",
    priorityReason: "須依最新合約付款條件完成月結設定。",
    relatedRiskIds: ["risk-reconciliation-cutoff"],
  },
  {
    id: "task-system-access",
    title: "盤點並移轉系統權限",
    description:
      "盤點原負責人的程式碼庫、雲端平台、監控與部署權限，依最小權限原則移轉給接手人。",
    status: "已完成",
    deadline: "2026-07-31",
    estimateHours: 4,
    department: "工程",
    sourceDocument: "系統權限矩陣.xlsx",
    isBlocking: true,
    riskLevel: "medium",
    crossDeptDependencyCount: 1,
    prerequisites: [],
    priority: "P1",
    priorityReason: "接手人需具備權限才能進行部署與事故處理。",
    relatedRiskIds: ["risk-access-scope"],
  },
  {
    id: "task-deployment-runbook",
    title: "演練正式環境部署流程",
    description:
      "由接手工程師依 runbook 完成一次預演，確認發布、資料庫遷移、監控與回滾步驟。",
    status: "進行中",
    deadline: "2026-08-02",
    estimateHours: 8,
    department: "工程",
    sourceDocument: "Production_Deployment_Runbook.md",
    isBlocking: false,
    riskLevel: "high",
    crossDeptDependencyCount: 0,
    prerequisites: [
      {
        taskId: "task-system-access",
        taskTitle: "盤點並移轉系統權限",
        status: "已完成",
        dependentDept: "工程",
        dependentOwner: "王柏鈞",
      },
    ],
    priority: "P1",
    priorityReason: "須在原負責人離職前驗證接手人能獨立發布。",
    relatedRiskIds: ["risk-access-scope"],
  },
  {
    id: "task-support-escalation",
    title: "更新客服升級與通報機制",
    description:
      "確認客訴分級、值班窗口、跨部門升級條件及重大事件的對客通知範本。",
    status: "待處理",
    deadline: "2026-08-04",
    estimateHours: 3,
    department: "客服",
    sourceDocument: "客服事件升級流程_v2.pptx",
    isBlocking: false,
    riskLevel: "medium",
    crossDeptDependencyCount: 2,
    prerequisites: [
      {
        taskId: "task-contract-handover",
        taskTitle: "移交客戶合約細節",
        status: "進行中",
        dependentDept: "法務",
        dependentOwner: "林冠宇",
      },
    ],
    priority: "P1",
    priorityReason: "客服需掌握合約 SLA 與客製承諾後才能正確分級。",
    relatedRiskIds: ["risk-contract-commitment"],
  },
  {
    id: "task-open-tickets",
    title: "交接未結客服案件",
    description:
      "逐案補齊處理紀錄、客戶期望、承諾回覆日期與下一步，並安排新舊負責人共同回訪。",
    status: "進行中",
    deadline: "2026-08-06",
    estimateHours: 7,
    department: "客服",
    sourceDocument: "未結案件追蹤表.xlsx",
    isBlocking: false,
    riskLevel: "medium",
    crossDeptDependencyCount: 1,
    prerequisites: [],
    priority: "P2",
    priorityReason: "避免負責人更換造成客戶重複說明或錯過承諾時程。",
    relatedRiskIds: [],
  },
  {
    id: "task-vendor-payments",
    title: "確認供應商付款與核准清單",
    description:
      "核對固定供應商、付款週期、請款憑證、費用歸屬及代理核准人，標記本月待付款項。",
    status: "已完成",
    deadline: "2026-08-08",
    estimateHours: 4,
    department: "財務",
    sourceDocument: "供應商付款作業手冊.pdf",
    isBlocking: false,
    riskLevel: "low",
    crossDeptDependencyCount: 1,
    prerequisites: [],
    priority: "P2",
    priorityReason: "付款資訊完整可降低重複付款與逾期風險。",
    relatedRiskIds: ["risk-reconciliation-cutoff"],
  },
  {
    id: "task-data-retention-review",
    title: "確認客戶資料保存與刪除規則",
    description:
      "依合約與內控規範確認客服附件、系統日誌及匯出資料的保存期限與刪除責任人。",
    status: "待處理",
    deadline: "2026-08-09",
    estimateHours: 5,
    department: "法務",
    sourceDocument: "客戶資料保存政策_2026.pdf",
    isBlocking: false,
    riskLevel: "low",
    crossDeptDependencyCount: 2,
    prerequisites: [
      {
        taskId: "task-contract-handover",
        taskTitle: "移交客戶合約細節",
        status: "進行中",
        dependentDept: "法務",
        dependentOwner: "林冠宇",
      },
    ],
    priority: "P3",
    priorityReason: "需先辨識合約例外，才能套用正確的資料保存期限。",
    relatedRiskIds: ["risk-data-retention"],
  },
];
